# Generated by Django 5.0.3 on 2024-03-07 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service', '0002_appointment_prescription_doctor_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('appointment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='service.appointment')),
                ('payment_time', models.DateTimeField(auto_now=True, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
