# Generated by Django 5.0.3 on 2024-03-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('membership_id', models.CharField(default='TYPE003', max_length=8, primary_key=True, serialize=False)),
                ('discount_percent', models.IntegerField(null=True)),
                ('type', models.CharField(default=3, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('service_name', models.CharField(max_length=50, null=True)),
                ('service_type', models.CharField(max_length=30, null=True)),
                ('status', models.IntegerField(default=2)),
                ('total_order', models.IntegerField(default=0)),
                ('total_payment', models.IntegerField(default=0)),
                ('lastbooking_date', models.DateField(null=True)),
            ],
        ),
    ]
