# Generated by Django 5.0.3 on 2024-03-07 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('cccd', models.CharField(max_length=50, null=True)),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('dob', models.DateField(null=True)),
                ('gender', models.IntegerField(null=True)),
                ('status', models.IntegerField(default=1, null=True)),
                ('service', models.ManyToManyField(to='service.service')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=50, null=True)),
                ('lastname', models.CharField(max_length=50, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('dob', models.DateField(default='2004-01-01')),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=50, null=True)),
                ('cccd', models.CharField(max_length=50, null=True)),
                ('bmi', models.FloatField(blank=True, max_length=20, null=True)),
                ('weight', models.FloatField(blank=True, max_length=20, null=True)),
                ('height', models.FloatField(blank=True, max_length=20, null=True)),
                ('blood_pressure', models.FloatField(blank=True, max_length=20, null=True)),
                ('total_order', models.IntegerField(default=0)),
                ('total_payment', models.IntegerField(default=0, null=True)),
                ('membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='service.membership')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
