# Generated by Django 5.0.3 on 2024-03-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_doctor_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
